{{- range .Values.reverse -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ print .name "-ingress" }}
  labels:
    {{- include "ingress.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ .backendProtocol | quote }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer }}
spec:
  ingressClassName: {{ $.Values.ingressClassName }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ print .name "-service" }}
            port:
              number: {{ .port }}
  tls:
  - hosts:
    -  {{ .host }}
    secretName: {{ print .host "-tls" }}
---
{{- end }}
