apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ print (include "foundry.fullname" .) "-backup" }}
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: alpine
              image: ghcr.io/danmor425/rsync:1.0.0
              command: ["rsync", "-av", "/source/", "/dest"]
              volumeMounts:
              - name: source
                mountPath: "/source"
              - name: dest
                mountPath: "/dest"
                subPath: foundry
          volumes:
          - name: source
            persistentVolumeClaim:
              claimName: {{ .Values.backupExistingClaim }}
          - name: dest
            persistentVolumeClaim:
              claimName: {{ .Values.nasExistingClaim }}
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1