apiVersion: v1
kind: Service
metadata:
  name: {{ include "foundry.fullname" . }}
  labels:
    {{- include "foundry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 30000
      protocol: TCP
      name: foundry-30000
  selector:
    {{- include "foundry.selectorLabels" . | nindent 4 }}